# Generated by Django 3.1.4 on 2023-03-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('SCHA', 'School Admin'), ('SCHT', 'School Teacher'), ('VLGA', 'Village Admin'), ('DSTA', 'District Admin'), ('RGNA', 'Region Admin'), ('STA', 'State Admin')], default='A', max_length=45),
        ),
    ]
