# Generated by Django 3.1.4 on 2024-05-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20240515_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('SCHA', 'School Admin'), ('SCHT', 'School Teacher'), ('VLGA', 'Village Admin'), ('DSTA', 'District Admin'), ('NGO', 'Partner Admin'), ('RGNA', 'Region Admin'), ('STA', 'State Admin')], default='A', max_length=45),
        ),
    ]
