# Generated by Django 3.1.4 on 2023-03-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='ownership',
            field=models.CharField(blank=True, choices=[('PBC', 'Rural'), ('PRV', 'Urban'), ('CMY', 'Community'), ('IDP', 'Internally Displaced Person')], max_length=5, null=True),
        ),
    ]
