# Generated by Django 3.1.4 on 2023-03-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20230307_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='ownership',
            new_name='location_type',
        ),
    ]
