# Generated by Django 3.1.4 on 2023-03-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_stream_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
