# Generated by Django 3.1.4 on 2023-04-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20230324_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='has_attended_pre_primary',
        ),
        migrations.AddField(
            model_name='student',
            name='is_overage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='pre_primary_attendend',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('Q', 'Quranic'), ('F', 'Formal')], max_length=3, null=True),
        ),
    ]
