# Generated by Django 3.1.4 on 2023-04-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20230403_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_overage',
            new_name='is_over_age',
        ),
    ]
