# Generated by Django 3.1.4 on 2023-04-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20230403_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='family_nick_name',
            field=models.CharField(blank=True, help_text="Grand Father's name", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, help_text="Grand Father's name", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, help_text="Father's name", max_length=200, null=True),
        ),
    ]
