# Generated by Django 3.1.4 on 2023-04-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_migrate_father_name_from_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('NE', 'Newly Enrolled'), ('PE', 'Re-Enrolled')], default='NE', max_length=5),
        ),
    ]
