# Generated by Django 3.1.4 on 2024-03-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('name', 'state')},
        ),
    ]
