# Generated by Django 3.1.4 on 2023-03-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TranslationLocal',
            new_name='TranslationLocale',
        ),
    ]
