# Generated by Django 3.1.4 on 2023-04-07 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0005_auto_20230407_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationtext',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='translationtext',
            name='title',
            field=models.TextField(max_length=500, unique=True),
        ),
        migrations.CreateModel(
            name='LocalTranslationText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('translated_text', models.TextField(max_length=600)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation.translationlocale')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation.translationtext')),
            ],
            options={
                'ordering': ('-text_id',),
                'unique_together': {('text', 'locale')},
            },
        ),
    ]
