# Generated by Django 3.1.4 on 2023-04-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0006_auto_20230407_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocalTranslationText',
            new_name='LocaleTranslationText',
        ),
    ]
