# Generated by Django 3.1.4 on 2023-04-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0007_auto_20230407_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localetranslationtext',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_translations', to='translation.translationlocale'),
        ),
        migrations.AlterField(
            model_name='localetranslationtext',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locale_translations', to='translation.translationtext'),
        ),
    ]
