# Generated by Django 3.1.4 on 2023-04-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0008_auto_20230407_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localetranslationtext',
            name='translated_text',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
