# Generated by Django 3.1.4 on 2023-04-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0009_auto_20230407_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationtext',
            name='example',
            field=models.JSONField(blank=True, default=True, null=True),
        ),
    ]
