# Generated by Django 3.1.4 on 2023-04-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0010_auto_20230408_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationlocale',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='translationtext',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
