# Generated by Django 3.1.4 on 2023-03-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Present'), (0, 'Absent')], default=0)),
                ('cause_of_absence', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('id',),
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='AttendanceHistory',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('present', models.IntegerField(default=0)),
                ('absent', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoAttendanceHistory',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Present'), (0, 'Absent')], default=0)),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
