# Generated by Django 3.1.4 on 2023-03-07 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
        migrations.AddField(
            model_name='noattendancehistory',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.stream'),
        ),
        migrations.AddField(
            model_name='attendancehistory',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.stream'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.stream'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student'),
        ),
    ]
