# Generated by Django 3.1.4 on 2023-03-24 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_stream_active'),
        ('attendance', '0002_auto_20230307_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='school.stream'),
        ),
    ]
