name: Django CI

on: [workflow_dispatch]

env:
  LIBRARY_PATH: /home/gocd/openssl/lib
  CPATH: /home/gocd/openssl/include
  openssl: /home/gocd/openssl/bin/openssl
  DESTINATION_FOLDER: /folder/path

jobs:
  build:
    name: Moe  Somali API
    runs-on: python1

    steps:
      - uses: actions/checkout@v3

      - name: Create Virtual Environment
        run: |
          virtualenv venv --python=python3.8
          mkdir test_static || true
          mkdir test_media || true

      # - name: Install Dependencies
      #   run: |
      #     source venv/bin/activate
      #     pip install -r requirements.txt

      # - name: Testing
      #   run: |
      #     source venv/bin/activate
      #     python manage.py test

    # - name: Run Tests
    #  run: |
    #   python manage.py test
